package com.plobin.sandbox

/**
 * Create TestServiceService class. 간단한 테스트 서비스
 * Generated by Kotlin File Generator
 */
class Create {

    fun execute(): String {
        return "Hello from Create!"
    }

    companion object {
        const val TAG = "Create"
    }
}
