package com.plobin.sandbox.model

import kotlinx.serialization.Serializable

/**
 * Create UserModel data class. User data model with email, name, and authentication info
 * Generated by Kotlin File Generator
 */
@Serializable
data class Create(
    val id: Long = 0,
    val name: String = "",
    val description: String = "",
    val isActive: Boolean = true,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
